pluginManagement {
    repositories {
        gradlePluginPortal()
        google()
        mavenCentral()
    }
}

dependencyResolutionManagement {
    repositories {
        mavenCentral()
        google()
        maven { url = uri('https://jitpack.io') }
    }
}

rootProject.name = 'example-game'
includeBuild('../rollercoaster')
